### ISSUE TITLE
Changes to the biome mapping in paintedbiomes.cfg are overwritten on startup

### ISSUE THREAD

**Issue by JakobOvrum** [maruohon/paintedbiomes#1] opened 2015-06-20 19:33 UTC
paintedbiomes.cfg had a bunch of conflicting color mappings, so I went in and fixed some of them so they were all unique. But my changes don't seem to be persistent; the mod just overwrites the changes every time the server starts, with seemingly random but eventually conflicting color mappings.

Using Biomes o' Plenty, Twilight Forest, Tropicraft and Thaumcraft, so there are quite a few biomes installed. I sorted out the biome IDs so they're all unique, so that shouldn't be an issue.

Is there a way to get persistent custom color mappings in paintedbiomes.cfg?

**Comment by maruohon** [comment] 2015-06-20 22:21
It should only add missing biomes, it shouldn't overwrite existing entries.
I was just staring at the config class for a few minutes, the only thing I can think of right now is maybe an issue with capitalization of the config entries/biome names. Is this on a dedicated server? Is the server on Linux, Windows or Mac? Unfortunately I don't have a dev environment available right now to test stuff.

**Comment by JakobOvrum** [comment] 2015-06-21 10:13
I'll see if I can reproduce this to get more information. I looked at the code and I can't see the issue either. If I can't reproduce it, maybe it was just a configuration error on my end (I was assigning biome IDs after all).

Dedicated server:
```
$ uname -a
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux
$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by maruohon** [comment] 2015-07-12 21:55
I can't reproduce this, and from what I've understood, the issue on your end fixed itself also? I just pushed a commit (doing a release soon) that changes/cleans up the biome id/color handling things quite a bit. I'm going to close this for now. If you still have the issue, feel free to re-open this.

**Closed by maruohon** 2015-07-12 21:55 UTC
